/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface SaaoPlotModal {

    }

    interface SaaoPlot {

    }
  }


    interface HTMLSaaoPlotModalElement extends StencilComponents.SaaoPlotModal, HTMLStencilElement {}

    var HTMLSaaoPlotModalElement: {
      prototype: HTMLSaaoPlotModalElement;
      new (): HTMLSaaoPlotModalElement;
    };
    

    interface HTMLSaaoPlotElement extends StencilComponents.SaaoPlot, HTMLStencilElement {}

    var HTMLSaaoPlotElement: {
      prototype: HTMLSaaoPlotElement;
      new (): HTMLSaaoPlotElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'saao-plot-modal': JSXElements.SaaoPlotModalAttributes;
    'saao-plot': JSXElements.SaaoPlotAttributes;
    }
  }

  namespace JSXElements {

    export interface SaaoPlotModalAttributes extends HTMLAttributes {

    }

    export interface SaaoPlotAttributes extends HTMLAttributes {

    }
  }

  interface HTMLElementTagNameMap {
    'saao-plot-modal': HTMLSaaoPlotModalElement
    'saao-plot': HTMLSaaoPlotElement
  }

  interface ElementTagNameMap {
    'saao-plot-modal': HTMLSaaoPlotModalElement;
    'saao-plot': HTMLSaaoPlotElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;