/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface SaaoPlotDetails {

    }
  }


    interface HTMLSaaoPlotDetailsElement extends StencilComponents.SaaoPlotDetails, HTMLStencilElement {}

    var HTMLSaaoPlotDetailsElement: {
      prototype: HTMLSaaoPlotDetailsElement;
      new (): HTMLSaaoPlotDetailsElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'saao-plot-details': JSXElements.SaaoPlotDetailsAttributes;
    }
  }

  namespace JSXElements {

    export interface SaaoPlotDetailsAttributes extends HTMLAttributes {

    }
  }

  interface HTMLElementTagNameMap {
    'saao-plot-details': HTMLSaaoPlotDetailsElement
  }

  interface ElementTagNameMap {
    'saao-plot-details': HTMLSaaoPlotDetailsElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;